### ISSUE TITLE
Default Weather Map Provider for the Weather Report Applet has Stopped Working

### ISSUE THREAD

**Issue by williamwiley** [mate-desktop/mate-applets#220]
The default weather map in the weather applet no longer works.

I've confirmed the issue exists for several US locations. Last map that it is able to pull is always November 30, 2016 around 1PM EST.

**Comment by flexiondotorg** [comment]
What distro and what version of libmateweather do you have installed? This issue was resolved some time ago.

**Comment by williamwiley** [comment]
So it's been fixed? I see.

Linux Mint Debian Edition 2, MATE 1.16.1, libmateweather 1.16.1-1+betsy

The problem is still present in whatever version I have. I've been using a custom map since I last posted, though.

**Comment by flexiondotorg** [comment]
Hmmm, you have the latest release of libmateweather. Are you behind a proxy? Can you try some other locations and see if you get weather data? I can't reproduce this issue 🙁

**Comment by williamwiley** [comment]
Not behind a proxy.

It's reproducible on other machines on my network with the same OS setup. Maybe it's OS specific?

Other maps for other locations all around the US give me the same problem. Last one I tried was Boston, MA, same result.

**Comment by flexiondotorg** [comment]
@monsta Can you reproduce this?

**Comment by monsta** [comment]
Confirmed, at least with the mentioned location (Boston, MA). Something's wrong with image.weather.com...
