### ISSUE TITLE
[GTK+3] Sticky Notes - Can't select text [$10]

### ISSUE THREAD

**Issue by philthynz** [mate-desktop/mate-applets#236]
After upgrading to 1.18 mate desktop. The sticky notes text can't be selected. The mouse pointer just grabs the note instead of selecting any text.

Running Ubuntu Mate 17.04

**Comment by philthynz** [comment]
This can be closed. I reposed here https://bugs.launchpad.net/ubuntu-mate/+bug/1675581

**Comment by raveit65** [comment]
I can confirm this issue here in fedora-26.
But open a report first in your distro is always a good idea, to give the distro maintainer a chance to verify if this is a distro related or not.
Thank you.

**Comment by monsta** [comment]
Confirmed in Debian Testing... is that another GTK+ 3.22 issue?

**Comment by raveit65** [comment]
> Confirmed in Debian Testing... is that another GTK+ 3.22 issue?

i get this with m-a-1.18.0 in f24 (3.20) too.

**Comment by raveit65** [comment]
Hmm, i see this too with f25 VM with mate-1.16 and gtk3.22.
Let see if this happens with rhel7.

**Comment by raveit65** [comment]
Same with m-a-1.17.0 inside rhel7 with 3.14.

**Comment by monsta** [comment]
Just checked gnome-applets, they have the same problem, so no fix to pick there.

**Comment by alunux** [comment]
Also, it affects the lock button. Type some text in sticky, click the lock button, and then click again to unlock, finally this issue is appeared.

**Comment by philthynz** [comment]
This affects xpad too. As a work around i am using [indicator-stickynotes](https://launchpad.net/~umang/+archive/ubuntu/indicator-stickynotes)

**Comment by monsta** [comment]
Well, xpad is a separate application. They probably have similar window grabbing code though... Did you file a bug report about it?

**Comment by philthynz** [comment]
Yes here https://bugs.launchpad.net/ubuntu/+source/mate-applets/+bug/1675581

**Comment by monsta** [comment]
No, I meant xpad bug :slightly_smiling_face:

**Comment by philthynz** [comment]
Ahh. No I havent

On 14/05/2017 7:18 PM, monsta <notifications@github.com> wrote:

No, I meant xpad bug 🙂

**Comment by oliver-joos** [comment]
This bug has been fixed in Gnome!
Ubuntu released the 2 patches on 2017-07-08, see https://launchpad.net/bugs/1703110

**Comment by muktupavels** [comment]
@oliver-joos no, patches does not fix problem with text selecting... first patch fix problem that notes are not saved, but second patch fix missing delete dialog.

**Comment by muktupavels** [comment]
... and text selection bug is also fixed, you know where to find it. Beer from everyone whose life becomes easier/better with this bug fix. :beer: :smile:

**Comment by oliver-joos** [comment]
Oops, my fault!

I saw that you added a link to the correct commit to the bug I mentioned above - many thanks! I did not find this one, although I searched quite a while.
For less confusion I referred your addition to the original bug report https://bugs.launchpad.net/bugs/1675581

**Comment by oliver-joos** [comment]
I just rebuilt mate-applets 1.18.1 on a Linux Mint 18.2 MATE (Live DVD) together with your patch.
The patch fixes this bug! Selecting text by mouse works again as expected.

Here is the patch I applied:
https://git.gnome.org/browse/gnome-applets/commit/?h=gnome-3-22&id=ac310d6a362db0ddb55ab9bc581a9c92a1c1fed0

**Comment by oliver-joos** [comment]
After some testing I found another bug when selecting text:
A text selection is not visible if "Use color from the system theme" is disabled (for current note or globally).

Do you agree that this is unrelated to this bug/your patch?

**Comment by muktupavels** [comment]
Yes, it is unrelated to this bug and/or my patch... Problem is gtk_widget_override_background_color function that overrides both backgrounds - text and selection. Proper way would be to create GtkCssProvider and add required CSS to change colors.

```
textview text { background: red; color: green}
textview text selection { background: blue; color: black; }
```

:beers:

**Comment by oliver-joos** [comment]
I am more used to wxWidgets than Gtk. I guess GtkCssProvider would be a good solution, but not a one-liner. Therefore I opened a new issue https://github.com/mate-desktop/mate-applets/issues/260

**Comment by muktupavels** [comment]
Sticky notes in gnome-applets now use GtkCssProvider...

**Comment by monsta** [comment]
@muktupavels: thanks, it works here. I've created https://github.com/mate-desktop/mate-applets/pull/276 for testing. How do I send you a beer? 🙂

**Comment by lukefromdc** [comment]
Confirmed here,testing https://github.com/mate-desktop/mate-applets/pull/276

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-applets/pull/276 works

**Comment by monsta** [comment]
Ok, fix merged.
@muktupavels: you can claim the bounty on Bountysource as it's your fix 🙂

**Comment by muktupavels** [comment]
On Wed, Sep 20, 2017 at 5:27 PM, monsta <notifications@github.com> wrote:

> @muktupavels <https://github.com/muktupavels>: thanks, it works here.
> I've created #276 <https://github.com/mate-desktop/mate-applets/pull/276>
> for testing. How do I send you a beer? 🙂
>
Paypal, patreon or by post (don't know if that is allowed :D)...

**Comment by monsta** [comment]
Hmm, there's no option to send a beer on paypal or patreon 😄

**Comment by monsta** [comment]
Fix is released in version 1.18.2.
